version: '3.8'
services:
  service-receipt:
    build: .
    container_name: service-receipt
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-GANTI_DENGAN_PASSWORD_KUAT}
    restart: unless-stopped